'use client';
import {useState} from 'react';
import {Clipboard,Check,MessageCircle,ShoppingBag,Globe2,UserRound} from 'lucide-react';

export default function ContactPage({lang,companyPhone,onHome}:{lang:'ar'|'en';companyPhone:string;onHome:()=>void}){
  const en=lang==='en';const t=(ar:string,eng:string)=>en?eng:ar;
  const phone=companyPhone.replace(/\D/g,'');const hasPhone=phone.length>=8&&phone.length<=15;
  const [draft,setDraft]=useState<{name:string;contact:string;inquiry:string;message:string}|null>(null);
  const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);
  const inquiries=[{id:'wholesale',ar:'طلب جملة',en:'Wholesale request'},{id:'export',ar:'التصدير',en:'Export'},{id:'account',ar:'حساب تاجر',en:'Trader account'},{id:'followup',ar:'متابعة طلب',en:'Order follow-up'},{id:'other',ar:'استفسار آخر',en:'Other inquiry'}];
  const summary=draft?[t('استفسار عبر رواق','Riwaq inquiry'),`${t('الاسم','Name')}: ${draft.name}`,`${t('وسيلة التواصل','Contact details')}: ${draft.contact}`,`${t('نوع الاستفسار','Inquiry type')}: ${en?inquiries.find(i=>i.id===draft.inquiry)?.en:inquiries.find(i=>i.id===draft.inquiry)?.ar}`,`${t('الرسالة','Message')}: ${draft.message}`].join('\n'):'';
  const whatsapp='https://wa.me/'+phone;
  return <main className="wrap contact-page">
    <div className="breadcrumb"><button type="button" onClick={onHome}>{t('الرئيسية','Home')}</button><span>/</span>{t('تواصل معنا','Contact us')}</div>
    <section className="contact-intro"><span className="eyebrow">{t('رواق للتجارة','RIWAQ TRADE')}</span><h1>{t('لنتحدث عن احتياجات متجرك','Let’s talk about your store')}</h1><p>{t('للاستفسار عن طلبات الجملة، حساب التاجر أو التصدير، جهّز تفاصيلك لتكون المتابعة أوضح وأسهل.','For wholesale orders, trader accounts or export inquiries, prepare your details for a clear conversation.')}</p></section>
    <div className="contact-layout"><aside className="contact-options"><div className="contact-whatsapp-card"><span className="contact-channel-icon"><MessageCircle size={28}/></span><h2>{t('تواصل عبر واتساب','Chat on WhatsApp')}</h2>{hasPhone?<><p>{t('تواصل مباشرة على رقم الشركة المحدد في الموقع.','Contact the company using the number configured on the site.')}</p><bdi className="contact-phone">+{phone}</bdi><a className="btn contact-whatsapp" href={whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle size={19}/>{t('فتح محادثة واتساب','Open WhatsApp chat')}</a></>:<><p id="contact-phone-note">{t('لم يُحدّد رقم واتساب الشركة في الموقع بعد. يمكنك تجهيز استفسارك ونسخه من النموذج.','The company WhatsApp number has not been configured yet. You can prepare and copy your inquiry using the form.')}</p><button type="button" className="btn contact-whatsapp" disabled aria-describedby="contact-phone-note"><MessageCircle size={19}/>{t('واتساب غير متاح حاليًا','WhatsApp currently unavailable')}</button></>}</div><div className="contact-topics"><h2>{t('كيف يمكننا مساعدتك؟','How can we help?')}</h2><div><ShoppingBag size={21}/><span>{t('طلبات الجملة والمنتجات','Wholesale orders & products')}</span></div><div><UserRound size={21}/><span>{t('حساب التاجر وقائمة الأسعار','Trader accounts & pricing')}</span></div><div><Globe2 size={21}/><span>{t('استفسارات التصدير','Export inquiries')}</span></div></div></aside>
      <section className="contact-form-panel"><h2>{t('جهّز استفسارك','Prepare your inquiry')}</h2><p id="contact-form-note" className="contact-form-note">{t('هذا النموذج يجهّز الرسالة للنسخ فقط؛ لا يرسلها ولا يحفظها لدى الشركة.','This form prepares a message to copy; it does not send it or save it with the company.')}</p><form aria-describedby="contact-form-note" onChange={()=>{setDraft(null);setCopied(false);setCopyError(false)}} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const value=(key:string)=>String(data.get(key)||'').trim();if(!value('name')||!value('contact')||!value('message'))return;setDraft({name:value('name'),contact:value('contact'),inquiry:value('inquiry'),message:value('message')});setCopied(false);setCopyError(false)}}><div className="contact-fields"><label htmlFor="contact-name">{t('الاسم','Name')}<input id="contact-name" name="name" autoComplete="name" required maxLength={120}/></label><label htmlFor="contact-details">{t('رقم الهاتف أو البريد الإلكتروني','Phone number or email')}<input id="contact-details" name="contact" autoComplete="off" dir="auto" required maxLength={160}/></label><label className="contact-field-full" htmlFor="contact-inquiry">{t('نوع الاستفسار','Inquiry type')}<select id="contact-inquiry" name="inquiry" required defaultValue=""><option value="" disabled>{t('اختر نوع الاستفسار','Select an inquiry type')}</option>{inquiries.map(i=><option key={i.id} value={i.id}>{en?i.en:i.ar}</option>)}</select></label><label className="contact-field-full" htmlFor="contact-message">{t('الرسالة','Message')}<textarea id="contact-message" name="message" rows={5} required maxLength={3000}/></label></div><button className="btn primary" type="submit">{t('تجهيز الرسالة','Prepare message')}</button></form>
      {draft&&<div className="contact-draft"><p role="status">{t('الرسالة جاهزة للنسخ. لم يتم إرسالها.','Your message is ready to copy. It has not been sent.')}</p><label htmlFor="contact-summary">{t('نص الاستفسار','Inquiry text')}</label><textarea id="contact-summary" readOnly value={summary} rows={7}/><div className="button-row"><button type="button" className="btn light" onClick={async()=>{try{await navigator.clipboard.writeText(summary);setCopied(true);setCopyError(false)}catch{setCopyError(true)}}}>{copied?<Check size={18}/>:<Clipboard size={18}/>} {copied?t('تم نسخ الرسالة','Message copied'):t('نسخ الرسالة','Copy message')}</button>{hasPhone&&<a className="btn contact-whatsapp" href={whatsapp+'?text='+encodeURIComponent(summary)} target="_blank" rel="noopener noreferrer">{t('فتح الرسالة في واتساب','Open message in WhatsApp')}</a>}</div>{copyError&&<p role="alert">{t('تعذر النسخ التلقائي. حدد النص أعلاه وانسخه يدويًا.','Automatic copying failed. Select the text above and copy it manually.')}</p>}</div>}
      </section></div>
  </main>;
}
