export type Product={id:number;ar:string;en:string;code:string;cat:number;price:number;unit:string;unitEn:string;min:number;available:boolean;image:string;gallery?:string[];badge?:string;desc:string;descEn:string;options:string[];colors?:{ar:string;en:string;hex:string;image?:string}[];sizes?:string[];unavailableVariants?:string[]};
export const assetSrc=(asset:string)=>asset.startsWith('blob:')||asset.startsWith('data:')||asset.startsWith('/')?asset:`/assets/${asset}.jpg`;
export const productImageSrc=(product:Product,colorIndex=0)=>assetSrc(product.colors?.[colorIndex]?.image||product.image);
export const productImageForOption=(product:Product,option:string)=>{
  const colorIndex=product.colors?.findIndex(c=>option.startsWith(`${c.ar} / ${c.en} · `))??-1;
  return productImageSrc(product,colorIndex<0?0:colorIndex);
};
export const categories=[{ar:'جميع المنتجات',en:'All products'},{ar:'رجالي',en:'Men',img:'men'},{ar:'نسائي',en:'Women',img:'women'},{ar:'أولاد',en:'Boys',img:'boys'},{ar:'بناتي',en:'Girls',img:'girls'}];
export const initialProducts:Product[]=[
{id:1,ar:'قميص رجالي كتان بقصّة مريحة',en:'Relaxed linen shirt',code:'RW-MN-001',cat:1,price:82,unit:'قطعة',unitEn:'piece',min:12,available:true,image:'men-shirt',badge:'الأكثر طلبًا',desc:'قميص كتان ناعم بقصّة مريحة وتفاصيل بسيطة، مناسب لتشكيلة الملابس اليومية.',descEn:'A soft linen shirt with a relaxed fit and clean detailing for everyday assortments.',options:['عاجي / Ivory · M'],colors:[{ar:'عاجي',en:'Ivory',hex:'#e9e5d8'},{ar:'رملي',en:'Sand',hex:'#bb9c79',image:'men-shirt-sand'},{ar:'كحلي',en:'Navy',hex:'#22364c',image:'men-shirt-navy'}],sizes:['S','M','L','XL']},
{id:2,ar:'تيشيرت رجالي قطني أساسي',en:'Essential cotton tee',code:'RW-MN-002',cat:1,price:45,unit:'قطعة',unitEn:'piece',min:24,available:true,image:'men-tee-white',badge:'جديد',desc:'تيشيرت قطني عملي بقصّة منتظمة ولمسة ناعمة، قطعة أساسية لكل موسم.',descEn:'A regular-fit cotton tee with a soft hand feel, an easy staple for every season.',options:['أبيض / White · M'],colors:[{ar:'أبيض',en:'White',hex:'#f5f2ea'},{ar:'أسود',en:'Black',hex:'#24262a',image:'men-tee-black'},{ar:'وردي هادئ',en:'Dusty rose',hex:'#bd8a90',image:'men-tee-rose'}],sizes:['S','M','L','XL']},
{id:3,ar:'بليزر نسائي بقصّة انسيابية',en:'Tailored relaxed blazer',code:'RW-WM-003',cat:2,price:155,unit:'قطعة',unitEn:'piece',min:6,available:true,image:'women-blazer',badge:'اختيار رِواق',desc:'بليزر نسائي بخطوط انسيابية وقصّة مريحة، سهل التنسيق مع الإطلالات العملية.',descEn:'An easy tailored blazer with fluid lines, designed for versatile workwear styling.',options:['رملي / Sand · M'],colors:[{ar:'رملي',en:'Sand',hex:'#c7ac91'},{ar:'أسود',en:'Black',hex:'#26272a',image:'women-blazer-black'}],sizes:['S','M','L']},
{id:4,ar:'فستان نسائي ميدي ناعم',en:'Soft midi dress',code:'RW-WM-004',cat:2,price:112,unit:'قطعة',unitEn:'piece',min:8,available:true,image:'women-dress-berry',badge:'جديد',desc:'فستان ميدي بتصميم هادئ وتفاصيل أنيقة للاستخدام اليومي والمناسبات البسيطة.',descEn:'A quietly elegant midi dress for everyday wear and understated occasions.',options:['توتي / Berry · M'],colors:[{ar:'توتي',en:'Berry',hex:'#8f456d'},{ar:'عاجي',en:'Ivory',hex:'#eee5dc',image:'women-dress'}],sizes:['S','M','L']},
{id:5,ar:'طقم أولاد قطني مريح',en:'Boys cotton two-piece set',code:'RW-BY-005',cat:3,price:76,unit:'طقم',unitEn:'set',min:12,available:true,image:'boys-set-blue',desc:'طقم قطني مكون من قطعتين بقصّة مريحة تتحمل حركة اليوم.',descEn:'A comfortable two-piece cotton set made for everyday movement.',options:['أزرق فاتح / Pale blue · 6Y'],colors:[{ar:'أزرق فاتح',en:'Pale blue',hex:'#a6bdc8'},{ar:'رملي',en:'Sand',hex:'#c9b69b',image:'boys-set-sand'}],sizes:['4Y','6Y','8Y','10Y']},
{id:6,ar:'بنطال رجالي بقصّة مستقيمة',en:'Straight-leg tailored trousers',code:'RW-MN-006',cat:1,price:98,unit:'قطعة',unitEn:'piece',min:12,available:false,image:'men-trousers',desc:'بنطال بقصّة مستقيمة وتفاصيل نظيفة للتنسيق اليومي.',descEn:'Clean straight-leg trousers for versatile everyday styling.',options:['رملي / Sand · M'],colors:[{ar:'رملي',en:'Sand',hex:'#baa587'},{ar:'كحلي',en:'Navy',hex:'#30465b',image:'men-trousers-navy'}],sizes:['S','M','L','XL']},
{id:7,ar:'فستان بناتي بتفاصيل ناعمة',en:'Girls gathered dress',code:'RW-GR-007',cat:4,price:88,unit:'قطعة',unitEn:'piece',min:12,available:true,image:'girls-dress-pink',badge:'جديد',desc:'فستان بناتي بقصّة مريحة وتفاصيل لطيفة تناسب تشكيلة الموسم.',descEn:'A comfortable gathered dress with delicate details for the season.',options:['وردي / Pink · 6Y'],colors:[{ar:'وردي',en:'Pink',hex:'#d7a5b6'},{ar:'عاجي',en:'Ivory',hex:'#e9decf',image:'girls-dress-ivory'}],sizes:['4Y','6Y','8Y','10Y']},
{id:8,ar:'كارديغان بناتي محبوك',en:'Girls knit cardigan',code:'RW-GR-008',cat:4,price:73,unit:'قطعة',unitEn:'piece',min:12,available:true,image:'girls-cardigan',desc:'كارديغان خفيف بنسيج ناعم، قطعة سهلة التنسيق مع الإطلالات اليومية.',descEn:'A lightweight soft-knit cardigan, easy to layer with everyday outfits.',options:['عاجي / Ivory · 6Y'],colors:[{ar:'عاجي',en:'Ivory',hex:'#e9e0ce'},{ar:'توتي',en:'Berry',hex:'#a46d8a',image:'girls-cardigan-berry'}],sizes:['4Y','6Y','8Y','10Y']}
];
export type CartLine={key:string;id:number;qty:number;option:string;price:number};
export type Order={id:string;date:string;status:string;items:CartLine[];total:number;currency:string;note:string;merchant:string};
export const sampleOrders:Order[]=[{id:'RW-2026-1042',date:'2026-09-24',status:'review',items:[{key:'1',id:1,qty:12,option:'عاجي / Ivory · M',price:82},{key:'3',id:3,qty:6,option:'رملي / Sand · M',price:155}],total:1914,currency:'₪',note:'يرجى التواصل لتأكيد الطلب.',merchant:'متجر الأفق'},{id:'RW-2026-1036',date:'2026-09-18',status:'confirmed',items:[{key:'4',id:4,qty:24,option:'توتي / Berry · M',price:112}],total:2688,currency:'₪',note:'',merchant:'متجر الأفق'},{id:'RW-2026-1021',date:'2026-09-10',status:'complete',items:[{key:'7',id:7,qty:12,option:'وردي / Pink · 6Y',price:88}],total:1056,currency:'₪',note:'',merchant:'متجر الأفق'}];
export const statuses:Record<string,{ar:string;en:string}>={review:{ar:'قيد المراجعة',en:'Under review'},confirmed:{ar:'تم التأكيد',en:'Confirmed'},complete:{ar:'مكتمل',en:'Completed'},cancelled:{ar:'ملغي',en:'Cancelled'}};
