'use client';
import {useState} from 'react';
import {Check, ImagePlus, Plus, Star, Trash2, X} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {assetSrc,type Product} from './data';

type Category={ar:string;en:string};
type Props={initial:Product|null;lang:'ar'|'en';categories:Category[];onClose:()=>void;onSave:(product:Product)=>boolean|Promise<boolean>};
type Color=NonNullable<Product['colors']>[number];
const validHex=(value:string)=>/^#[0-9a-fA-F]{6}$/.test(value);

export default function ProductEditor({initial,lang,categories,onClose,onSave}:Props){
 const en=lang==='en';const t=(ar:string,english:string)=>en?english:ar;
 const [draft,setDraft]=useState<Product>(()=>{
  const base:Product={id:0,ar:'',en:'',code:'',cat:1,price:0,unit:'قطعة',unitEn:'piece',min:1,available:true,image:'',gallery:[],desc:'',descEn:'',options:[],colors:[],sizes:[],unavailableVariants:[]};
  return {...base,...initial,gallery:[...(initial?.gallery||[])],colors:(initial?.colors||[]).map(c=>({...c})),sizes:[...(initial?.sizes||[])],options:[...(initial?.options||[])],unavailableVariants:[...(initial?.unavailableVariants||[])]};
 });
 const [error,setError]=useState('');const [activePreview,setActivePreview]=useState('');
 const [sizesText,setSizesText]=useState((initial?.sizes||[]).join(', '));
 const update=(patch:Partial<Product>)=>{setDraft(x=>({...x,...patch}));setError('')};
 const updateColor=(index:number,patch:Partial<Color>)=>update({colors:(draft.colors||[]).map((c,i)=>i===index?{...c,...patch}:c)});
 const gallery=[draft.image,...(draft.gallery||[])].filter(Boolean);
 const preview=activePreview&&gallery.includes(activePreview)?activePreview:draft.image;
 const addFiles=(files:FileList|null,target:'gallery'|'color',index=0)=>{
  if(!files?.length)return;
  const selected=Array.from(files);
  if(selected.some(f=>!f.type.startsWith('image/')||f.size>10*1024*1024)){setError(t('اختر صورًا بصيغة صورة وبحجم لا يتجاوز 10MB للصورة.','Choose image files no larger than 10 MB each.'));return}
  if(target==='gallery'){
   const free=8-gallery.length;
   if(selected.length>free){setError(t('يمكن إضافة 8 صور أساسية كحد أقصى.','You can add up to 8 product photos.'));return}
   const urls=selected.map(f=>URL.createObjectURL(f));
   update({image:draft.image||urls[0],gallery:draft.image?[...(draft.gallery||[]),...urls]:[...(draft.gallery||[]),...urls.slice(1)]});
  }else updateColor(index,{image:URL.createObjectURL(selected[0])});
 };
 const setCover=(src:string)=>{if(src===draft.image)return;update({image:src,gallery:[...(draft.gallery||[]).filter(x=>x!==src),...(draft.image?[draft.image]:[])]});setActivePreview(src)};
 const removeImage=(src:string)=>{const remaining=gallery.filter(x=>x!==src);update({image:src===draft.image?(remaining[0]||''):draft.image,gallery:remaining.slice(src===draft.image?1:0).filter(x=>x!==draft.image)});setActivePreview('')};
 const submit=async(event:React.FormEvent<HTMLFormElement>)=>{
  event.preventDefault();
  if(!draft.image){setError(t('أضف صورة أساسية واحدة على الأقل للمنتج.','Add at least one product photo.'));return}
  const colors=(draft.colors||[]).map(c=>({...c,ar:c.ar.trim(),en:c.en.trim(),hex:c.hex.toUpperCase()}));
  if(colors.some(c=>!c.ar||!c.en||!validHex(c.hex))){setError(t('أكمل اسم اللون بالعربية والإنجليزية وكود HEX الصحيح لكل لون.','Complete both color names and a valid HEX code for each color.'));return}
  if(new Set(colors.map(c=>c.ar.toLowerCase())).size!==colors.length||new Set(colors.map(c=>c.en.toLowerCase())).size!==colors.length){setError(t('اسم اللون مكرر. استخدم اسمًا مختلفًا لكل لون.','Color names must be unique.'));return}
  const sizes=(draft.sizes||[]).map(x=>x.trim()).filter(Boolean);
  if(colors.length&&!sizes.length){setError(t('أضف مقاسًا واحدًا على الأقل عند استخدام الألوان.','Add at least one size when colors are set.'));return}
  const options=colors.length?colors.flatMap(c=>sizes.map(size=>`${c.ar} / ${c.en} · ${size}`)):draft.options.map(x=>x.trim()).filter(Boolean);
  if(!options.length){setError(t('أضف الألوان والمقاسات أو خيار بيع واحدًا على الأقل.','Add colors and sizes or at least one selling option.'));return}
  const validVariants=(draft.unavailableVariants||[]).filter(x=>options.includes(x));
  const saved={...draft,ar:draft.ar.trim(),en:draft.en.trim(),code:draft.code.trim(),unit:draft.unit.trim(),unitEn:draft.unitEn.trim(),colors,sizes,options,unavailableVariants:validVariants};
  if(await onSave(saved))onClose();
 };
 return <Dialog open={!!initial} onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="product-editor-dialog" dir={en?'ltr':'rtl'} showCloseButton={false}>
  <div className="product-editor-head"><div><span className="product-editor-kicker">{t('إدارة المنتجات','PRODUCT MANAGEMENT')}</span><DialogTitle>{draft.id?t('تعديل المنتج','Edit product'):t('إضافة منتج جديد','Add a product')}</DialogTitle><DialogDescription>{t('أدخل البيانات والصور والألوان في مكان واحد. التغييرات ضمن هذه الجلسة التجريبية.','Enter details, photos and colors in one place. Changes last for this demo session.')}</DialogDescription></div><button type="button" className="product-editor-close" onClick={onClose} aria-label={t('إغلاق','Close')}><X size={20}/></button></div>
  <form id="product-editor-form" onSubmit={submit} className="product-editor-form"><div className="product-editor-layout"><div className="product-editor-fields">
   <section className="product-editor-section"><div className="product-section-head"><span>01</span><div><h3>{t('بيانات المنتج','Product details')}</h3><p>{t('الاسم والكود والتصنيف ومعلومات الطلب.','Name, code, category and ordering details.')}</p></div></div><div className="product-edit-grid">
    <label>{t('اسم المنتج بالعربية','Arabic product name')}<input required value={draft.ar} onChange={e=>update({ar:e.target.value})} placeholder={t('مثال: قميص كتان رجالي','E.g. linen shirt')}/></label>
    <label>{t('اسم المنتج بالإنجليزية','English product name')}<input required dir="ltr" value={draft.en} onChange={e=>update({en:e.target.value})} placeholder="Linen shirt"/></label>
    <label>{t('كود المنتج','Product code')}<input required dir="ltr" value={draft.code} onChange={e=>update({code:e.target.value})} placeholder="RW-MN-001"/></label>
    <label>{t('التصنيف','Category')}<select value={draft.cat} onChange={e=>update({cat:Number(e.target.value)})}>{categories.slice(1).map((c,i)=><option key={i} value={i+1}>{en?c.en:c.ar}</option>)}</select></label>
    <label>{t('وحدة البيع بالعربية','Unit in Arabic')}<input required value={draft.unit} onChange={e=>update({unit:e.target.value})}/></label>
    <label>{t('وحدة البيع بالإنجليزية','Unit in English')}<input required dir="ltr" value={draft.unitEn} onChange={e=>update({unitEn:e.target.value})}/></label>
    <label>{t('الحد الأدنى للطلب','Minimum order quantity')}<input required type="number" min="1" step="1" value={draft.min} onChange={e=>update({min:Number(e.target.value)})}/></label>
    <label>{t('السعر الأساسي (₪)','Base price (₪)')}<input required type="number" min="0" step="0.01" value={draft.price} onChange={e=>update({price:Number(e.target.value)})}/></label>
    <label className="product-edit-full">{t('الوصف بالعربية','Arabic description')}<textarea rows={2} value={draft.desc} onChange={e=>update({desc:e.target.value})}/></label>
    <label className="product-edit-full">{t('الوصف بالإنجليزية','English description')}<textarea rows={2} dir="ltr" value={draft.descEn} onChange={e=>update({descEn:e.target.value})}/></label>
   </div></section>
   <section className="product-editor-section"><div className="product-section-head"><span>02</span><div><h3>{t('الصور الأساسية','Product photos')}</h3><p>{t('ارفع عدة صور، ثم اختر صورة الغلاف التي تظهر أولًا.','Upload multiple photos and choose the cover shown first.')}</p></div></div><div className="product-photo-grid">{gallery.map((src,i)=><div className="product-upload-tile" key={src}><button type="button" className="product-upload-preview" onClick={()=>setActivePreview(src)} aria-label={t('معاينة الصورة','Preview photo')+' '+(i+1)}><img src={assetSrc(src)} alt=""/></button><div className="product-upload-actions"><button type="button" className={src===draft.image?'is-cover':''} onClick={()=>setCover(src)} title={t('تعيين كغلاف','Set as cover')} aria-label={t('تعيين الصورة كغلاف','Set photo as cover')}><Star size={15}/>{src===draft.image?t('الغلاف','Cover'):t('اجعلها غلافًا','Set cover')}</button><button type="button" onClick={()=>removeImage(src)} aria-label={t('حذف الصورة','Remove photo')}><Trash2 size={15}/></button></div></div>)}{gallery.length<8&&<label className="product-add-photo"><ImagePlus size={29}/><strong>{gallery.length?t('أضف صورًا','Add photos'):t('ارفع صور المنتج','Upload product photos')}</strong><small>{t('يمكن اختيار عدة صور · حتى 8 صور','Select multiple · up to 8 photos')}</small><input type="file" accept="image/*" multiple onChange={e=>{addFiles(e.target.files,'gallery');e.target.value=''}}/></label>}</div></section>
   <section className="product-editor-section"><div className="product-section-head"><span>03</span><div><h3>{t('الألوان وصورها','Colors and their photos')}</h3><p>{t('لكل لون: اسم عربي وإنجليزي، كود اللون، وصورة اختيارية.','For each color: Arabic and English names, HEX code and an optional photo.')}</p></div></div><div className="product-color-list">{(draft.colors||[]).map((color,i)=><article className="product-color-card" key={i}><div className="product-color-top"><span className="product-color-swatch" style={{background:validHex(color.hex)?color.hex:'#eee'}}/><strong>{t('لون','Color')} {i+1}</strong><button type="button" onClick={()=>update({colors:draft.colors?.filter((_,index)=>index!==i)})} aria-label={t('حذف اللون','Remove color')}><Trash2 size={17}/></button></div><div className="product-color-details"><div className="product-edit-grid"><label>{t('اسم اللون بالعربية','Arabic color name')}<input required value={color.ar} onChange={e=>updateColor(i,{ar:e.target.value})} placeholder={t('مثل: كحلي','E.g. Navy')}/></label><label>{t('اسم اللون بالإنجليزية','English color name')}<input required dir="ltr" value={color.en} onChange={e=>updateColor(i,{en:e.target.value})} placeholder="Navy"/></label><label className="product-edit-full">{t('كود اللون HEX','Color HEX code')}<div className="product-hex-field"><input type="color" value={validHex(color.hex)?color.hex:'#b41f71'} aria-label={t('اختر اللون','Pick color')} onChange={e=>updateColor(i,{hex:e.target.value})}/><input required dir="ltr" value={color.hex} maxLength={7} pattern="#[0-9a-fA-F]{6}" placeholder="#22364C" onChange={e=>updateColor(i,{hex:e.target.value})}/></div></label></div><div className="product-color-photo">{color.image||draft.image?<img src={assetSrc(color.image||draft.image)} alt=""/>:<span className="product-color-photo-empty"><ImagePlus size={24}/></span>}<div><strong>{color.image?t('صورة هذا اللون','Photo for this color'):t('تُستخدم صورة الغلاف حاليًا','Using the cover photo')}</strong><label><ImagePlus size={16}/>{color.image?t('تغيير الصورة','Replace photo'):t('إضافة صورة اللون','Add color photo')}<input type="file" accept="image/*" onChange={e=>{addFiles(e.target.files,'color',i);e.target.value=''}}/></label>{color.image&&<button type="button" onClick={()=>updateColor(i,{image:undefined})}>{t('إزالة صورة اللون','Remove color photo')}</button>}</div></div></div></article>)}<button type="button" className="product-add-color" onClick={()=>update({colors:[...(draft.colors||[]),{ar:'',en:'',hex:'#b41f71'}]})}><Plus size={18}/>{t('إضافة لون آخر','Add another color')}</button></div></section>
   <section className="product-editor-section"><div className="product-section-head"><span>04</span><div><h3>{t('المقاسات والتوفر','Sizes and availability')}</h3><p>{t('افصل المقاسات بفاصلة؛ ترتبط المقاسات بكل لون.','Separate sizes with commas; sizes apply to each color.')}</p></div></div><div className="product-edit-grid"><label className="product-edit-full">{t('المقاسات','Sizes')}<input dir="ltr" value={sizesText} onChange={e=>{setSizesText(e.target.value);update({sizes:e.target.value.split(',').map(x=>x.trim())})}} placeholder="S, M, L, XL"/></label>{!(draft.colors||[]).length&&<label className="product-edit-full">{t('خيارات البيع (خيار في كل سطر)','Selling options (one per line)')}<textarea rows={2} value={(draft.options||[]).join('\n')} onChange={e=>update({options:e.target.value.split('\n')})} placeholder={t('افتراضي / Default','Default')}/></label>}<label className="product-edit-full">{t('خيارات غير متوفرة (اختياري)','Unavailable variants (optional)')}<textarea rows={2} value={(draft.unavailableVariants||[]).join('\n')} onChange={e=>update({unavailableVariants:e.target.value.split('\n')})} placeholder={t('اسم اللون بالعربية / English · M','Arabic color / English · M')}/></label></div><label className="product-availability"><input type="checkbox" checked={draft.available} onChange={e=>update({available:e.target.checked})}/><span>{t('متوفر للطلب','Available to order')}</span></label></section>
  </div><aside className="product-editor-aside"><span className="product-editor-kicker">{t('معاينة مباشرة','LIVE PREVIEW')}</span><div className="product-editor-preview"><div className="product-preview-image">{preview?<img src={assetSrc(preview)} alt=""/>:<div><ImagePlus size={31}/><span>{t('أضف صورة للمعاينة','Add a photo to preview')}</span></div>}</div><div className="product-preview-body"><small>{en?categories[draft.cat]?.en:categories[draft.cat]?.ar} · <bdi>{draft.code||'RW-...'}</bdi></small><h3>{(en?draft.en:draft.ar)||t('اسم المنتج','Product name')}</h3><p>{t('الحد الأدنى','Minimum')} <bdi>{draft.min||1}</bdi> {en?draft.unitEn:draft.unit}</p><div className="product-preview-swatches">{(draft.colors||[]).map((c,i)=><span key={i} title={en?c.en:c.ar} style={{background:validHex(c.hex)?c.hex:'#eee'}}/>)}</div></div></div><p className="product-editor-note"><Check size={17}/>{t('صور الألوان تظهر عند اختيار اللون في بطاقة المنتج وتفاصيله.','Color photos appear when a color is selected in the product card and details.')}</p></aside></div>
  {error&&<p className="product-editor-error" role="alert">{error}</p>}<div className="product-editor-footer"><span>{t('التغييرات في هذه الجلسة فقط','Changes in this demo session only')}</span><div><button type="button" className="product-editor-cancel" onClick={onClose}>{t('إلغاء','Cancel')}</button><button type="submit" className="product-editor-save">{t('حفظ المنتج','Save product')}</button></div></div></form>
 </DialogContent></Dialog>;
}
