'use client';
import {useState} from 'react';
import {ArrowUpLeft, Check, CheckCircle2, ClipboardList, Copy, Globe2, LayoutGrid, MessageCircle, Package, ShoppingBag, Store, Tags} from 'lucide-react';

type Category={ar:string;en:string};
type Props={kind:'traders'|'export';lang:'ar'|'en';categories:Category[];onCatalog:()=>void;onSignIn:()=>void;onWhatsApp:()=>void;onOther:()=>void;onHome:()=>void};

export default function TradePage({kind,lang,categories,onCatalog,onSignIn,onWhatsApp,onOther,onHome}:Props){
 const en=lang==='en', abroad=kind==='export';
 const t=(ar:string,english:string)=>en?english:ar;
 const [summary,setSummary]=useState('');
 const [copied,setCopied]=useState(false);
 const title=abroad?t('رِواق بلا حدود','Riwaq Beyond Borders'):t('رِواق للتجّار','Riwaq for Traders');
 const steps=abroad?[
  [t('اكتشف التشكيلة','Explore the collection'),t('تصفح القطع والألوان والمقاسات والحد الأدنى لكل منتج.','Browse pieces, colors, sizes and each product’s minimum.'),LayoutGrid],
  [t('ادخل بحساب تجارتك','Enter your trade account'),t('اطلع على قائمة الأسعار والعملة المخصصة لحسابك.','See the price list and currency assigned to your account.'),Tags],
  [t('جهّز طلبك','Prepare your request'),t('أرسل الأصناف والكميات من السلة لتحصل على رقم مرجعي للمتابعة.','Submit items and quantities from the cart for a follow-up reference.'),ClipboardList]
 ]:[
  [t('اختر ما يلائم متجرك','Choose for your store'),t('تنقل بين تشكيلات الرجال والنساء والأطفال في كتالوج واحد.','Explore men’s, women’s and children’s collections in one catalog.'),LayoutGrid],
  [t('راجع تفاصيل القطعة','Review each piece'),t('حدد اللون والمقاس والكمية مع وضوح الحد الأدنى للطلب.','Select colors, sizes and quantities with a clear minimum.'),Package],
  [t('أرسل طلب الجملة','Send your wholesale request'),t('راجع سلتك وأرسلها للشركة للمتابعة، دون دفع إلكتروني.','Review your cart and submit it for company follow-up, without online payment.'),ShoppingBag]
 ];
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{
  e.preventDefault();
  const data=new FormData(e.currentTarget);
  const value=(key:string)=>String(data.get(key)||'').trim();
  const lines=[title,`${t('النشاط / المتجر','Business / store')}: ${value('business')}`,`${t('جهة التواصل','Contact person')}: ${value('contact')}`,`${t('رقم التواصل','Contact number')}: ${value('phone')}`,`${abroad?t('البلد / السوق','Country / market'):t('المدينة / المنطقة','City / area')}: ${value('place')}`,`${t('الاهتمام','Interest')}: ${value('category')}`,`${t('الكمية المتوقعة','Estimated quantity')}: ${value('volume')||'—'}`,`${t('تفاصيل إضافية','Additional details')}: ${value('note')||'—'}`];
  setSummary(lines.join('\n'));setCopied(false);
 };
 const copy=async()=>{try{await navigator.clipboard.writeText(summary);setCopied(true)}catch{setCopied(false)}};
 return <main className={'trade-page '+(abroad?'trade-export':'trade-local')}>
  <div className="wrap trade-breadcrumb"><button onClick={onHome}>{t('الرئيسية','Home')}</button><span>/</span><span>{title}</span></div>
  <section className="trade-hero"><div className="wrap trade-hero-inner"><div className="trade-hero-copy">
   <span className="trade-kicker">{abroad?<Globe2 size={17}/>:<Store size={17}/>} {abroad?t('من رِواق إلى آفاق أوسع','FROM RIWAQ TO WIDER MARKETS'):t('شراكة تبدأ من متجرك','A PARTNERSHIP FOR YOUR STORE')}</span>
   <h1>{title}</h1><p>{abroad?t('تشكيلة أزياء جملة لعلاقات تجارية تتجاوز الحدود. استكشف الكتالوج، واطّلع على سعرك بعملة حسابك، وجهّز طلبًا واضحًا تتابعه الشركة معك.','Wholesale fashion for trade beyond borders. Explore the catalog, view pricing in your account currency and prepare a clear request for company follow-up.'):t('مساحة مصممة لتاجر الملابس الذي يبحث عن خيارات واضحة وخطوات طلب سهلة. من اختيار القطع إلى متابعة طلب الجملة، كل التفاصيل في مكان واحد.','A space for fashion traders who value clear choices and a simple request journey. From selecting pieces to following up on your wholesale request, everything is in one place.')}</p>
   <div className="trade-hero-actions"><button className="trade-button main" onClick={onCatalog}>{t('استكشف الكتالوج','Explore the catalog')}<ArrowUpLeft size={18}/></button><button className="trade-button secondary" onClick={onSignIn}>{t('دخول التاجر','Trader sign in')}</button></div>
   <div className="trade-hero-meta"><span><Check size={17}/>{t('كتالوج رجال ونساء وأطفال','Men, women & kids')}</span><span><Check size={17}/>{t('أسعار مرتبطة بحسابك','Account-specific pricing')}</span></div>
  </div><div className="trade-hero-visual"><img src={abroad?'/assets/hero-video-poster.jpg':'/assets/women.jpg'} alt={t('تشكيلة أزياء رِواق','Riwaq fashion collection')}/><div className="trade-image-note"><span>R / {abroad?'02':'01'}</span><strong>{abroad?t('أفق تجارتك أوسع','Your trade, wider'):t('اختيارات تليق بتجارتك','Made for your trade')}</strong></div></div></div></section>
  <section className="wrap trade-intro"><div className="trade-intro-heading"><span className="trade-section-mark">{abroad?'02 / EXPORT':'01 / TRADE'}</span><h2>{abroad?t('من أول قطعة إلى فرصة جديدة','From the first piece to a new opportunity'):t('كل خطوة محسوبة لمتجرك','Every step shaped for your store')}</h2></div><p>{abroad?t('رِواق يجمع عرض المنتجات وخياراتها وطلبات الجملة في تجربة واحدة. يحدد حسابك قائمة الأسعار وعملتها، وتتم متابعة التفاصيل التجارية بعد إرسال الطلب.','Riwaq brings products, options and wholesale requests into one experience. Your account sets the price list and currency, while commercial details are followed up after submission.'):t('اعرف تفاصيل المنتج قبل إضافته، وابنِ سلتك بالكميات المناسبة، ثم احتفظ برقم الطلب لتسهيل متابعته.','See product details before adding them, build your cart with suitable quantities and keep the reference number for follow-up.')}</p></section>
  <section className="wrap trade-journey"><div className="trade-section-title"><span className="trade-section-mark">{t('كيف تبدأ','THE JOURNEY')}</span><h2>{abroad?t('مسار واضح لأعمالك خارج الحدود','A clear path for business across borders'):t('رحلتك مع رِواق، ببساطة','Your Riwaq journey, simply')}</h2></div><div className="trade-steps">{steps.map(([heading,body,Icon],i)=><article key={i}><span className="trade-step-number">0{i+1}</span><Icon size={27} strokeWidth={1.7}/><h3>{heading as string}</h3><p>{body as string}</p></article>)}</div></section>
  <section className="trade-feature-band"><div className="wrap trade-feature-inner"><div><span className="trade-section-mark">{t('في كتالوج رِواق','IN THE RIWAQ CATALOG')}</span><h2>{abroad?t('الخيارات أمامك، والقرار لتجارتك','See the options. Choose for your business.'):t('تفاصيل صغيرة، قرار أفضل','The details behind a better choice')}</h2><p>{t('تصفح القطع حسب القسم، واعرف الخيارات المتوفرة والحد الأدنى للكمية. بعد الدخول تظهر أسعار القائمة المخصصة لحسابك وعملتها.','Browse by category and see available options and minimum quantities. Sign in to view your assigned price list and its currency.')}</p><button className="trade-inline-link" onClick={onCatalog}>{t('تصفح المنتجات','Browse products')} <ArrowUpLeft size={18}/></button></div><div className="trade-feature-tiles"><div><LayoutGrid/><strong>{t('أقسام متعددة','Curated categories')}</strong><span>{t('للرجال والنساء والأطفال','For men, women and kids')}</span></div><div><Tags/><strong>{t('سعر خاص بحسابك','Your account price')}</strong><span>{t('قائمة وأسعار بعملتها','A list with its currency')}</span></div><div><ClipboardList/><strong>{t('طلب قابل للمتابعة','A traceable request')}</strong><span>{t('برقم مرجعي واضح','With a clear reference')}</span></div></div></div></section>
  <section className="wrap trade-inquiry" id="trade-inquiry"><div className="trade-inquiry-copy"><span className="trade-section-mark">{t('عرّفنا على تجارتك','TELL US ABOUT YOUR BUSINESS')}</span><h2>{abroad?t('لنفتح باب الحوار','Let’s start the conversation'):t('ابدأ الحديث عن متجرك','Tell us about your store')}</h2><p>{t('جهّز نبذة سريعة عن نشاطك واحتياجاتك، ثم انسخها وشاركها عبر قناة التواصل المناسبة. هذه المعاينة لا ترسل البيانات تلقائيًا.','Prepare a brief overview of your business and needs, then copy it to share through your preferred channel. This preview does not send data automatically.')}</p><div className="trade-contact-card"><MessageCircle size={23}/><div><strong>{t('تفضّل المحادثة المباشرة؟','Prefer a direct conversation?')}</strong><span>{t('افتح واتساب الشركة للتواصل بشأن احتياجات تجارتك.','Open the company WhatsApp to discuss your needs.')}</span></div><button onClick={onWhatsApp}>{t('تواصل الآن','Get in touch')} <ArrowUpLeft size={16}/></button></div></div>
   <div className="trade-form-card">{summary?<div className="trade-summary" role="status"><CheckCircle2 size={37}/><h3>{t('ملخصك جاهز','Your brief is ready')}</h3><p>{t('انسخه وشاركه مع الشركة. لم تُرسل البيانات من هذه الصفحة.','Copy and share it with the company. Nothing was sent from this page.')}</p><pre dir="auto">{summary}</pre><div className="trade-form-actions"><button className="trade-button main" onClick={copy}><Copy size={17}/>{copied?t('تم النسخ','Copied'):t('نسخ الملخص','Copy brief')}</button><button className="trade-button outline" onClick={()=>{setSummary('');setCopied(false)}}>{t('تعديل البيانات','Edit details')}</button></div></div>:<form onSubmit={submit}><h3>{abroad?t('بطاقة اهتمام بالتصدير','Export interest brief'):t('بطاقة تعريف التاجر','Trader introduction')}</h3><p>{t('بضع تفاصيل تساعدك على بدء محادثة واضحة.','A few details to start a clear conversation.')}</p><div className="trade-form-grid"><label>{t('اسم النشاط / المتجر','Business / store name')}<input name="business" required maxLength={100} placeholder={t('اسم متجرك','Your store name')}/></label><label>{t('اسم مسؤول التواصل','Contact person')}<input name="contact" required maxLength={100} placeholder={t('الاسم الكامل','Full name')}/></label><label>{t('رقم التواصل','Contact number')}<input name="phone" required type="tel" dir="ltr" maxLength={30} placeholder="+970 ..."/></label><label>{abroad?t('البلد / السوق المستهدف','Country / target market'):t('المدينة / المنطقة','City / area')}<input name="place" required maxLength={100} placeholder={abroad?t('البلد أو السوق','Country or market'):t('مدينتك','Your city')}/></label><label>{t('القسم الذي يهمك','Category of interest')}<select name="category" required defaultValue=""><option value="" disabled>{t('اختر القسم','Choose a category')}</option>{categories.slice(1).map(c=><option key={c.en} value={en?c.en:c.ar}>{en?c.en:c.ar}</option>)}<option value={t('تشكيلة متنوعة','Mixed collection')}>{t('تشكيلة متنوعة','Mixed collection')}</option></select></label><label>{t('الكمية المتوقعة (اختياري)','Estimated quantity (optional)')}<input name="volume" maxLength={60} placeholder={t('مثال: حسب الأصناف المختارة','E.g. depends on selected items')}/></label><label className="trade-wide">{t('ما الذي تبحث عنه؟ (اختياري)','What are you looking for? (optional)')}<textarea name="note" rows={4} maxLength={500} placeholder={t('أخبرنا عن القطع أو طبيعة تجارتك…','Tell us about styles or your business…')}/></label></div><button className="trade-button main trade-submit" type="submit">{t('جهّز ملخص الاهتمام','Prepare my brief')} <ArrowUpLeft size={17}/></button></form>}</div>
  </section>
  <section className="wrap trade-next"><div><span>{t('اكتشف المسار الآخر','EXPLORE ANOTHER PATH')}</span><h2>{abroad?t('تعمل داخل السوق المحلي؟','Working in your local market?'):t('تبحث عن آفاق أبعد؟','Looking beyond borders?')}</h2></div><button onClick={onOther}>{abroad?t('رِواق للتجّار','Riwaq for Traders'):t('رِواق بلا حدود','Riwaq Beyond Borders')} <ArrowUpLeft size={19}/></button></section>
 </main>;
}
