from django.urls import path

from shop.api.admin_views import (
    AdminCategoryDetailView,
    AdminCategoryListView,
    AdminCurrencyDetailView,
    AdminCurrencyListView,
    AdminInvoiceDetailView,
    AdminInvoiceListView,
    AdminLoginView,
    AdminLogoutView,
    AdminMeView,
    AdminOrderDetailView,
    AdminOrderListView,
    AdminOrderStatusView,
    AdminPriceListDetailView,
    AdminPriceListListView,
    AdminPriceListPricesView,
    AdminProductColorImageView,
    AdminProductDetailView,
    AdminProductImageDetailView,
    AdminProductImageListView,
    AdminProductListView,
    AdminSettingsView,
    AdminTraderDetailView,
    AdminTraderListView,
    AdminTraderPasswordView,
    BulkImportView,
)

urlpatterns = [
    path("auth/login/", AdminLoginView.as_view(), name="admin-login"),
    path("auth/logout/", AdminLogoutView.as_view(), name="admin-logout"),
    path("auth/me/", AdminMeView.as_view(), name="admin-me"),
    path("products/bulk-import/", BulkImportView.as_view(), name="admin-bulk-import"),
    path("products/", AdminProductListView.as_view(), name="admin-products"),
    path("products/<int:product_id>/", AdminProductDetailView.as_view(), name="admin-product-detail"),
    path("products/<int:product_id>/images/", AdminProductImageListView.as_view(), name="admin-product-images"),
    path(
        "products/<int:product_id>/images/<int:image_id>/",
        AdminProductImageDetailView.as_view(),
        name="admin-product-image-detail",
    ),
    path(
        "products/<int:product_id>/colors/<int:color_id>/image/",
        AdminProductColorImageView.as_view(),
        name="admin-product-color-image",
    ),
    path("categories/", AdminCategoryListView.as_view(), name="admin-categories"),
    path("categories/<int:category_id>/", AdminCategoryDetailView.as_view(), name="admin-category-detail"),
    path("traders/", AdminTraderListView.as_view(), name="admin-traders"),
    path("traders/<str:trader_id>/", AdminTraderDetailView.as_view(), name="admin-trader-detail"),
    path("traders/<str:trader_id>/set-password/", AdminTraderPasswordView.as_view(), name="admin-trader-password"),
    path("currencies/", AdminCurrencyListView.as_view(), name="admin-currencies"),
    path("currencies/<str:code>/", AdminCurrencyDetailView.as_view(), name="admin-currency-detail"),
    path("price-lists/", AdminPriceListListView.as_view(), name="admin-price-lists"),
    path("price-lists/<str:price_list_id>/", AdminPriceListDetailView.as_view(), name="admin-price-list-detail"),
    path("price-lists/<str:price_list_id>/prices/", AdminPriceListPricesView.as_view(), name="admin-price-list-prices"),
    path("orders/", AdminOrderListView.as_view(), name="admin-orders"),
    path("orders/<str:order_number>/", AdminOrderDetailView.as_view(), name="admin-order-detail"),
    path("orders/<str:order_number>/status/", AdminOrderStatusView.as_view(), name="admin-order-status"),
    path("invoices/", AdminInvoiceListView.as_view(), name="admin-invoices"),
    path("invoices/<str:invoice_id>/", AdminInvoiceDetailView.as_view(), name="admin-invoice-detail"),
    path("settings/", AdminSettingsView.as_view(), name="admin-settings"),
]
